### ISSUE TITLE
[Feature] Replay (<<) and Fast Forward (>>)

### ISSUE THREAD

**Issue by jesherman** [jame25/Piper-Read#1]
Putting some suggested improvements here in case they're quick/easy!

One in particular is since its generating a .wav to playback, perhaps adding a quick replay / fast forward (5 seconds) would be useful for re-hearing specific parts of a converted passage

**Comment by jame25** [comment]
I've spent much of the past week trying to implement these features.

<img width="383" alt="preaderFF" src="https://github.com/jame25/Piper-Read/assets/13631646/7b9406cc-f00a-4b8c-b958-c450a0577563">

However, I have only managed to get "Skip Forward" working - skip forward one paragraph. "Replay" functionality is much more complex, and I'm not even entirely sure it's possible with NAudio - at this time. I hope to revisit this issue in the future.

How would you feel if I included "Skip Forward" and have 'read from cursor position' functionality as a compromise to replay content?

**Comment by jesherman** [comment]
this is a very reasonable implementation - thanks! 

my suspicion is that the only way to get more granular control would be per-sentence sequential conversion vs looking for paragraphs (e.g. search for [.] or [,] vs line breaks and avoid [...], but i wonder if that has a possible effect of reducing playback quality (i presume the model works better when reading multiple paragraphs but would have to test to know more)
