### ISSUE TITLE
Speed dial only works before conversion

### ISSUE THREAD

**Issue by jesherman** [jame25/Piper-Read#2]
Adjusting speed of the voice only works before conversion -- i assume this is because it generates a static .wav -- it also lacks an indicator (1 - 0.5?)

This makes it limited situationally since you may want to increase/decrease the speed as you're working through a large text file/article

**Comment by jesherman** [comment]
update - for 1.5 it will now adjust after each paragraph which is pretty good! Probably a lot harder to go beyond this given the limitations of per-paragraph generation w/ Piper so I'd say this is good enough but will let you close to confirm if this is the intended behavior now

**Comment by jame25** [comment]
v1.0.6 is as good as I can get it for now. Perhaps Piper TTS themselves will improve things in this area in the future.
