### ISSUE TITLE
Dictionary Rules

### ISSUE THREAD

**Issue by jesherman** [jame25/Piper-Read#4]
Add / allow dictionary rules or other customization for improved transcription. 

e.g. pattern of phrases to skip transcribing -- example of words like "Getty Images" or references to "image text" or presence of pipes (|)

if possible, allow detection to skip a whole line of transcription if a banned word is detected (so it skips those lines during transcription)

**Comment by jame25** [comment]
Try out the latest release and let me know what you think.
https://github.com/jame25/Piper-Read/releases/tag/v1.0.3

**Comment by jesherman** [comment]
Thanks - is it checking .dict on a comma space basis or per line?

**Comment by jame25** [comment]
> Thanks - is it checking .dict on a comma space basis or per line?

Per line.

**Comment by jesherman** [comment]
It doesn't appear to work for me. 

I have the following passage I tested:

Lee Smith | Reuters
The blockbuster diabetes drug Ozempic could be manufactured for less than $5 a month, even as Novo Nordisk charges close to $1,000 per month for the injection in the U.S. before insurance, a study released Wednesday suggests.

It reads the whole thing. I put | in line 1 of banned.dict

**Comment by jame25** [comment]
Try this version: https://github.com/jame25/Piper-Read/releases/tag/v1.0.4

It's working for me. 

Note: I changed skip sentence to skip line.

**Comment by jesherman** [comment]
works! ty
