### ISSUE TITLE
punctuation detection seems off

### ISSUE THREAD

**Issue by jesherman** [jame25/Piper-Read#5]
with default piper it seems punctuation is off and speeds through pauses in large paragraphs/sentences. - reading this attached issue is this something that can be resolved through piper-read? Seems to require a tweak to how piper phoenmizes

https://github.com/rhasspy/piper/issues/122
https://github.com/rhasspy/piper-phonemize

**Comment by jesherman** [comment]
for 1.5 this has improved but I am still noticing the TTS a bit "off" -- I actually think there may even be a difference in pitch(?) I ran the exact paragraph in my Home Assistant instance and noticed it a lot more "slow" and normal at 1.0 vs. this program running at 1.0 (same issue where it seems to speak commas/periods too quickly) 

You may want to try running the same paragraphs btwn piper-read and another program and i'm curious if you notice different or similar results

**Comment by jame25** [comment]
You are absolutely correct. Well spotted. Pitch is the issue; specifically pitch of audio playback via NAudio.

I have uploaded a new version (1.0.5d) that matches (to my ears) wav-based [Piper Tray](https://github.com/jame25/Piper-Tray) @ speed 1.0.

https://github.com/jame25/Piper-Read/releases/tag/v1.0.5

**Comment by jesherman** [comment]
punctuation works great now!
