### ISSUE TITLE
[bug] pause button goes out of sync at end of paragraphs

### ISSUE THREAD

**Issue by jesherman** [jame25/Piper-Read#6]
In 1.5 preview, if you pause right at the end of a paragraph (showing "resume" as the option on the button), piper will begin processing the next paragraph. At the end of processing the next paragraph, it switches the "resume" back to "pause". Piper still continues to "pause" recitation.

Pressing pause maintains that state, and pressing resume restarts playback.

**Comment by jame25** [comment]
Hi, thanks for the report. I am however not able to reproduce this bug in v1.0.6.

https://github.com/jame25/Piper-Read/releases/tag/v1.0.6
