### ISSUE TITLE
No Sound output, Appears to process

### ISSUE THREAD

**Issue by RangeyRover** [jame25/Piper-Read#7]
I have the latest piper windows release, 2 different voices, including the libritts_r default.
Piper read in same directory.
Piper read runs and when I press convert gives a brief pause when stop appears but I hear no sound output.

**Comment by jame25** [comment]
Make sure the voice filenames match. For example, en_US-libritts_r-medium.onnx.json **NOT** en_en_US_libritts_r_medium_en_US-libritts_r-medium.onnx.json
