### ISSUE TITLE
multiple voices

### ISSUE THREAD

**Issue by signalstop** [jame25/Piper-Read#8]
Is there a way to change the default voice on multivoices like 

en_GB-semaine-medium.onnx

  "num_speakers": 4,
  "speaker_id_map": {
    "prudence": 0,
    "spike": 1,
    "obadiah": 2,
    "poppy": 3

The default is prudence but I like the spike voice. I don't see a way to switch multi voices using Piper-Read

An example of this implemented would be in Piper Tray:

https://github.com/jame25/Piper-Tray

setting is stored int the system.conf

**Comment by jame25** [comment]
Sure, as you point out, I recently added support in Piper Tray and can do the same for Piper Read. I will try to make it happen in the coming days.

**Comment by jame25** [comment]
Try out this new version: https://github.com/jame25/Piper-Read/releases/tag/v1.0.9

**Comment by signalstop** [comment]
> Try out this new version: https://github.com/jame25/Piper-Read/releases/tag/v1.0.9

Thank you! It works great : )  One minor issue is the pause/resume doesn't seem to be working. When I pause resume, (for me) it seems to skip a paragraph when it resumes. Sometimes when I hit pause it starts jumping paragraph to paragraph saying the first word. If it's not behaving like that for you, ignore this. It's minor as I can stop and restart.  I wonder if it's the buffer.  It does start speaking noticeably faster now with the buffer. Thanks for adding the ability to select the speaker!

**Comment by jame25** [comment]
Apologies, I missed that issue. It should be fixed now: https://github.com/jame25/Piper-Read/releases/tag/v1.1.0

**Comment by signalstop** [comment]
> Apologies, I missed that issue. It should be fixed now: https://github.com/jame25/Piper-Read/releases/tag/v1.1.0

Confirmed fixed. Thanks!
